name: GitHub Check Changed Files
on:
  push:
    branches:
      - master
    paths-ignore:
      - "**/README.md"
jobs:
  changedfiles:
    runs-on: [ubuntu-latest]
    env:
      FILE_EXT: .txt
    # Map a step output to a job output
    outputs:
      all: ${{ steps.changes.outputs.all }}
      filtered: ${{ steps.changes.outputs.filtered }}
    steps:
      # Make sure we have some code to diff.
      - name: Checkout repository
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: Get changed files
        id: changes
        # Set outputs using the command.
        run: |
          echo "::set-output name=all::$(git diff-tree --name-only --no-commit-id -r --diff-filter=ACMRT ${{ github.event.pull_request.base.sha }} ${{ github.sha }} | xargs)"
          echo "::set-output name=filtered::$(git diff-tree --name-only --diff-filter=ACMRT ${{ github.event.pull_request.base.sha }} ${{ github.sha }} | grep ${{ env.FILE_EXT }}$ | xargs)"
      - name: Log changed files
        id: logchanges
        run: |
          echo filtered
          for i in ${{ steps.changes.outputs.filtered }}
          do
              echo $i
          done
  lint:
    runs-on: [ubuntu-latest]
    # require the first job to have ran
    needs: changedfiles
    # only run there are changed files
    if: ${{ needs.changedfiles.outputs.filtered }}
    steps:
      - name: echo changed files
        run: echo ${{ needs.changedfiles.outputs.filtered }}
